__author__ = "sokunheng"
__version__ = "2.5.0"
__description_en__ = "Download, Edit, and Generate Videos, Images and Sounds, in bulk using AI"
__reponame__ = "DownEdit"
__repourl__ = "https://github.com/sokunheng/DownEdit"